# Generated by Django 4.0 on 2022-01-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='postimg/'),
            preserve_default=False,
        ),
    ]
