# Generated by Django 4.0 on 2022-02-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='user',
            new_name='users',
        ),
    ]
