# Generated by Django 4.0 on 2022-02-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_user_blogcomments_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomments',
            old_name='users',
            new_name='user',
        ),
    ]
